name: "Trabalho - Executar Testes com Mocha"

on:
  push:
  workflow_dispatch:

jobs:
  teste_unitario:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Instalando Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Instalando o Yarn
        run: npm install -g yarn

      - name: Instalando as dependências do projeto
        run: yarn

      - name: Instalar mocha
        run: npm install mocha

      - name: Execução dos testes unitários com Mocha
        run: npx mocha .\teste.js
